// src/components/kb/AskPanel.jsx
// The answer card: cited answer, confidence, sources, and ways to close the loop (save / add missing knowledge).
import { Fragment } from "react";
import { useNavigate } from "react-router-dom";
import { LuSparkles, LuCopy, LuFilePlus2, LuX, LuCpu, LuCircleHelp } from "react-icons/lu";
import { Tooltip } from "../ui/primitives";
import { toast } from "../ui/toast";
import { TypeIcon, VerifiedMark } from "./bits";

function Citation({ n, source, onOpen }) {
  return (
    <Tooltip label={source?.title || `Source ${n}`}>
      <button
        onClick={() => source && onOpen(source._id || source.id)}
        className="inline-grid place-items-center min-w-[18px] h-[18px] px-1 mx-0.5 -translate-y-px rounded-[5px] bg-accent-soft text-accent text-[10.5px] font-semibold tabular-nums align-middle hover:bg-accent hover:text-white transition-colors"
      >
        {n}
      </button>
    </Tooltip>
  );
}

function AnswerText({ text, sourceFor, onOpen }) {
  const lines = text.split("\n").filter(Boolean);
  const render = (line) =>
    line.split(/(\[\d+\])/g).map((part, i) => {
      const m = /^\[(\d+)\]$/.exec(part);
      return m ? <Citation key={i} n={Number(m[1])} source={sourceFor(Number(m[1]))} onOpen={onOpen} /> : <Fragment key={i}>{part}</Fragment>;
    });
  const isList = lines.every((l) => l.startsWith("• ") || l.startsWith("- "));
  if (isList) {
    return (
      <ul className="space-y-1.5">
        {lines.map((l, i) => (
          <li key={i} className="flex gap-2">
            <span className="mt-[9px] size-1 rounded-full bg-faint shrink-0" />
            <span>{render(l.replace(/^[•-]\s/, ""))}</span>
          </li>
        ))}
      </ul>
    );
  }
  return (
    <div className="space-y-2">
      {lines.map((l, i) => (
        <p key={i}>{render(l)}</p>
      ))}
    </div>
  );
}

export default function AskPanel({ question, result, loading, onClose, onSave, onAddMissing }) {
  const navigate = useNavigate();
  const open = (id) => navigate(`/kb/${id}`);

  if (loading) {
    return (
      <div className="card p-5" style={{ animation: "var(--animate-rise)" }}>
        <p className="flex items-center gap-2 text-[12.5px] font-medium text-accent">
          <LuSparkles size={14} />
          Searching team knowledge
          <span className="flex gap-0.5">
            {[0, 1, 2].map((i) => (
              <span key={i} className="size-1 rounded-full bg-accent" style={{ animation: `typing 1s ease-in-out ${i * 0.15}s infinite` }} />
            ))}
          </span>
        </p>
        <div className="mt-4 space-y-2">
          <span className="skeleton block h-3.5 w-full" />
          <span className="skeleton block h-3.5 w-11/12" />
          <span className="skeleton block h-3.5 w-2/3" />
        </div>
      </div>
    );
  }
  if (!result) return null;

  const empty = !result.answer;
  // Map citation numbers to the memories that were ranked for this answer
  const sourceFor = (n) => result.citations?.find((c) => c.ref === n) || null;
  const confidence = Math.round((result.confidence || 0) * 100);
  const cited = new Set((result.citations || []).map((c) => String(c.id)));

  return (
    <div className="card overflow-hidden" style={{ animation: "var(--animate-rise)" }}>
      <div className="flex items-center gap-2 px-5 pt-4">
        <span className="grid place-items-center size-6 rounded-md bg-accent text-white">
          <LuSparkles size={13} />
        </span>
        <p className="text-[13px] font-semibold text-ink truncate">{question}</p>
        <Tooltip label={result.mode === "ai" ? `Generated by ${result.model} from your knowledge` : "Extracted from your knowledge by the local engine — no data leaves your workspace"}>
          <span className="chip h-5 text-[10.5px] ml-auto shrink-0">
            <LuCpu size={10} /> {result.mode === "ai" ? "AI" : "Local engine"}
          </span>
        </Tooltip>
        <button className="icon-btn size-6" onClick={onClose} aria-label="Close answer">
          <LuX size={13} />
        </button>
      </div>

      {empty ? (
        <div className="px-5 py-4">
          <p className="flex items-center gap-2 text-[14px] text-ink-2">
            <LuCircleHelp size={15} className="text-faint" /> The Knowledge Base doesn't know this yet.
          </p>
          <p className="text-[13px] text-muted mt-1">If you find out, add it so the next person gets an instant answer.</p>
          <button className="btn btn-sm btn-secondary mt-3" onClick={onAddMissing}>
            <LuFilePlus2 size={13} /> Add this to the Knowledge Base
          </button>
        </div>
      ) : (
        <>
          <div className="px-5 pt-3 pb-4 text-[14px] leading-[1.75] text-ink-2">
            <AnswerText text={result.answer} sourceFor={sourceFor} onOpen={open} />
          </div>
          <div className="flex items-center gap-3 px-5 pb-4">
            <Tooltip label="How much of your question the cited knowledge covers">
              <span className="flex items-center gap-2 text-[11.5px] text-muted">
                Confidence
                <span className="w-16 h-1.5 rounded-full bg-subtle overflow-hidden">
                  <span
                    className="block h-full rounded-full origin-left"
                    style={{ width: `${confidence}%`, background: confidence >= 70 ? "var(--color-ok)" : confidence >= 40 ? "var(--color-warn)" : "var(--color-danger)", animation: "grow-x 700ms var(--ease-out-expo) both" }}
                  />
                </span>
                <span className="tabular-nums">{confidence}%</span>
              </span>
            </Tooltip>
            <span className="ml-auto flex items-center gap-1">
              <button
                className="btn btn-sm btn-ghost"
                onClick={() => navigator.clipboard?.writeText(result.answer.replace(/\s?\[\d+\]/g, "")).then(() => toast.success("Answer copied"))}
              >
                <LuCopy size={13} /> Copy
              </button>
              <button className="btn btn-sm btn-ghost" onClick={onSave}>
                <LuFilePlus2 size={13} /> Save as knowledge
              </button>
            </span>
          </div>
        </>
      )}

      {result.sources?.length > 0 && (
        <div className="border-t border-line bg-canvas/60 px-5 py-3">
          <p className="text-[11px] font-medium text-faint mb-1.5">{empty ? "Closest matches" : "Sources"}</p>
          <div className="grid sm:grid-cols-2 gap-1.5">
            {result.sources.slice(0, 4).map((s) => {
              const c = result.citations?.find((x) => String(x.id) === String(s._id));
              return (
                <button
                  key={s._id}
                  onClick={() => open(s._id)}
                  className={`flex items-start gap-2 p-2 rounded-lg text-left bg-surface transition-shadow hover:shadow-[var(--shadow-raised)] ${cited.has(String(s._id)) ? "" : "opacity-70"}`}
                  style={{ boxShadow: "var(--shadow-card)" }}
                >
                  {c ? (
                    <span className="grid place-items-center size-[18px] rounded-[5px] bg-accent-soft text-accent text-[10.5px] font-semibold shrink-0 mt-px">{c.ref}</span>
                  ) : (
                    <TypeIcon type={s.type} size={13} />
                  )}
                  <span className="min-w-0">
                    <span className="flex items-center gap-1">
                      <span className="text-[12.5px] font-medium text-ink truncate">{s.title}</span>
                      <VerifiedMark verified={s.verified} stale={s.stale} size={11} />
                    </span>
                    <span className="block text-[11.5px] text-muted line-clamp-1">{s.snippet}</span>
                  </span>
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
